In [2]:
import numpy as np
m = 4
n = 6

A = np.random.randn(m,n)
B = np.random.randn(n,m)

C1 = np.zeros((m,m))
for i in range(n):
    C1 = C1 + np.outer(A[:,i],B[i,:])
    
C2 = A@B

C1 - C2

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 5.55111512e-17,  0.00000000e+00, -2.22044605e-16,
         1.11022302e-16],
       [-1.11022302e-16,  0.00000000e+00,  2.22044605e-16,
        -3.33066907e-16],
       [ 5.55111512e-17,  0.00000000e+00, -4.44089210e-16,
        -4.44089210e-16]])

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import math
v = np.array([ 3, -2 ])
thetas = np.linspace(0,2*np.pi,100)
vecmags = np.zeros((len(thetas),2))

for i in range(len(thetas)):
    th = thetas[i]
    A1 = np.array([[2*math.cos(th), -math.sin(th)], [math.sin(th), math.cos(th)]])
    A2 = np.array([[math.cos(th), -math.sin(th)], [math.sin(th), math.cos(th)]])
    
    vecmags[i,0] = np.linalg.norm(A1@v.T)
    vecmags[i,1] = np.linalg.norm(A2@v.T)
                   
plt.plot(thetas,vecmags,'o-')
plt.xlabel('Roatation angle (rad.)')
plt.ylabel('Av magnitude')
plt.legend(['inmpure rotation','pure rotation'])
plt.show()

<Figure size 640x480 with 1 Axes>

In [4]:
x = np.linspace(-np.pi,np.pi,100)
xy = np.vstack((np.cos(x),np.sin(x))).T
print(np.shape(xy))

plt.plot(xy[:,0],xy[:,1],'o')

T = np.array([[1,2],[2,1]])
newxy = xy@T

plt.plot(newxy[:,0],newxy[:,1],'o')

plt.axis('square')
plt.show()

(100, 2)


In [5]:
m = 3
A = np.random.randn(m,m)
AtA = A.T@A

B = np.random.randn(m,m)
BtB = B.T@B

#compute sum, multiplication and Hadamard multiplication
Cs = AtA + BtB
Cm = AtA @ BtB
Ch = AtA * BtB# Hadamard

print(Cs-Cs.T),print(' ')
print(Cm-Cm.T),print(' ')
print(Ch-Ch.T)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 
[[ 0.          6.1334195  -7.35234124]
 [-6.1334195   0.          7.49114055]
 [ 7.35234124 -7.49114055  0.        ]]
 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
A = np.random.randn(4,4)
D = np.diag(np.random.randn(4))

print(A@A),print(' ')
print(A*A),print(' ')

print(D@D),print(' ')
print(D*D)

[[ 1.88758679 -1.17201309  2.18084704 -0.39685049]
 [ 5.90978536 -2.98592504 -1.98618409 -0.1326206 ]
 [ 0.79554417  2.09856189  0.74952748  0.60976466]
 [ 0.49173663 -4.25704417  2.5623038   2.6739719 ]]
 
[[9.96783984e-02 1.17015786e+00 5.65215224e-01 2.59938687e-01]
 [4.55143123e-01 3.35029023e-02 4.54938051e+00 2.83443574e-01]
 [6.25212819e+00 4.61756908e-01 2.76461118e-01 4.75150394e-01]
 [1.56521466e+00 2.49091904e+00 3.82083769e-03 2.83376676e+00]]
 
[[0.26786069 0.         0.         0.        ]
 [0.         2.82431984 0.         0.        ]
 [0.         0.         0.20341255 0.        ]
 [0.         0.         0.         0.18329444]]
 
[[0.26786069 0.         0.         0.        ]
 [0.         2.82431984 0.         0.        ]
 [0.         0.         0.20341255 0.        ]
 [0.         0.         0.         0.18329444]]


In [18]:
m = 5
A = np.random.randn(m,m)
A = A@A.T

v = np.random.randn(m)
w = np.random.randn(m)

np.dot(A@v,w) - np.dot(v,A@w)

0.0