# 36.matrix-scalar multiplication

In [3]:
import numpy as np

In [4]:
m = 7
n = 5

A = np.random.randn(m,n)
B = np.random.randn(m,n)

s = np.random.randn()

resL = s * (A+B)
resR = s*A + s*B

print(resL), print(' ')
print(resR), print(' ')

print(resL - resR)

[[-3.97923004  1.89435654 -2.16529274 -0.83360422 -4.57324449]
 [-3.32759087 -1.76064087  0.58189863 -1.52600506  2.83439193]
 [-6.54401193  0.06060891 -1.34665448 -1.26776807  0.17790783]
 [ 0.68979992 -2.37622444  0.33520576 -0.67815426  2.24220554]
 [ 3.26459795 -5.9357526   1.74821905 -4.46111975  6.69192817]
 [-4.16000843  2.29029048 -2.06338822  1.78265527  0.85186317]
 [-4.77424689  1.12457563  6.19848375  0.17372514  4.09098925]]
 
[[-3.97923004  1.89435654 -2.16529274 -0.83360422 -4.57324449]
 [-3.32759087 -1.76064087  0.58189863 -1.52600506  2.83439193]
 [-6.54401193  0.06060891 -1.34665448 -1.26776807  0.17790783]
 [ 0.68979992 -2.37622444  0.33520576 -0.67815426  2.24220554]
 [ 3.26459795 -5.9357526   1.74821905 -4.46111975  6.69192817]
 [-4.16000843  2.29029048 -2.06338822  1.78265527  0.85186317]
 [-4.77424689  1.12457563  6.19848375  0.17372514  4.09098925]]
 
[[-4.44089210e-16  0.00000000e+00  0.00000000e+00  1.11022302e-16
   8.88178420e-16]
 [ 8.88178420e-16 -2.220446

# 40.linearity of trace

In [8]:
m = n = 4

A = np.random.randn(m,n)
B = np.random.randn(m,n)

l = np.random.rand()
print('tr(A+B) = ' + str(np.trace(A+B)) )
print('tr(A)+tr(B) = '+ str(np.trace(A) + np.trace(B)))

tr(A+B) = -2.7213741976762735
tr(A)+tr(B) = -2.7213741976762735
