In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [6]:

A = np.random.randn(10,4)
B = np.random.randn(4,10)
C = A@B
print(np.shape(C))
print(np.linalg.matrix_rank(C))
print(C)
m = 8
n = 47
r = 3

A = np.random.randn(m,r) @ np.random.randn(r,n)
# print(A)

(10, 10)
4
[[ 0.45529847 -0.38649596 -1.61427315  1.58474719  0.09252944  2.76352066
   0.10309894  0.79999183 -0.16024471 -0.40224894]
 [-1.3307815   0.87961668  2.96484786 -2.73589274 -0.02519485 -3.33409516
  -1.3629283   0.50870389 -0.27282544  1.52929336]
 [-2.37893733  1.15172854  3.30996883 -2.30254893  2.1333361   1.90899927
  -3.33104957  5.27155878  0.06105203  2.77918609]
 [ 2.07486862  0.31278607 -1.33856835  1.31871104 -1.92624067 -0.74256495
  -0.16540653 -1.60101857 -0.82211439 -0.21970202]
 [ 4.8478315  -0.5981046  -4.43752881  4.89420273  0.40586547  4.43058741
   2.51137312 -2.7269473   2.09124334 -2.97639197]
 [-0.62780856  0.92891128  2.53575446 -1.26284617  3.10825864  2.25042561
  -1.56074176  3.22447014  1.93634199  1.2292858 ]
 [ 0.48502536 -0.48969134 -1.31937684  0.9735224  -0.52695852  0.33474567
   0.90043183 -0.99868759 -0.17426467 -0.80717973]
 [-0.97116667 -0.47986393  0.21008844 -0.63335335  0.16613602 -1.03405457
   0.90206305 -0.66851793  0.08694222 -0

In [11]:
v = np.array([[1,2,3,4]]).T

S = np.vstack(([4,3,6,2],[0,4,0,1])).T
T = np.vstack(([1,2,2,2],[0,0,1,2])).T
print(S)

Sv = np.concatenate((S,v),axis=1)
Tv = np.concatenate((T,v),axis=1)
print(Sv)

print(' ')
print(np.linalg.matrix_rank(Sv))
print(np.linalg.matrix_rank(Tv))

[[4 0]
 [3 4]
 [6 0]
 [2 1]]
[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]
 
3
2
